### ISSUE TITLE
AttributeError: module 'cgpt' has no attribute 'lattice_rank_sum'

### ISSUE THREAD

**Issue by jfy4** [lehner/gpt#124]
Running the "pure_gauge.py" hmc script from applications results in the following error:

```
SharedMemoryNone: SharedMemoryAllocate 1073741824 GPU implementation 
0SharedMemoryNone:  SharedMemoryNone.cc acceleratorAllocDevice 1073741824bytes at 0x7f8d92000000 for comms buffers 

__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
__|_ |  |  |  |  |  |  |  |  |  |  |  | _|__
__|_                                    _|__
__|_   GGGG    RRRR    III    DDDD      _|__
__|_  G        R   R    I     D   D     _|__
__|_  G        R   R    I     D    D    _|__
__|_  G  GG    RRRR     I     D    D    _|__
__|_  G   G    R  R     I     D   D     _|__
__|_   GGGG    R   R   III    DDDD      _|__
__|_                                    _|__
__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
__|__|__|__|__|__|__|__|__|__|__|__|__|__|__
  |  |  |  |  |  |  |  |  |  |  |  |  |  |  


Copyright (C) 2015 Peter Boyle, Azusa Yamaguchi, Guido Cossu, Antonin Portelli and other authors

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
Current Grid git commit hash=76c294a7bae149e9e52b980396a4265c77d3d2d1: (HEAD -> feature/gpt, origin/feature/gpt, origin/HEAD) clean

Grid : Message : ================================================ 
Grid : Message : MPI is initialised and logging filters activated 
Grid : Message : ================================================ 
Grid : Message : Requested 1073741824 byte stencil comms buffers 
Grid : Message : MemoryManager::Init() setting up
Grid : Message : MemoryManager::Init() cache pool for recent allocations: SMALL 8 LARGE 2
Grid : Message : MemoryManager::Init() Unified memory space

=============================================
              Initialized GPT                
     Copyright (C) 2020 Christoph Lehner     
=============================================
GPT :       0.329332 s : Initializing gpt.random(hmc-pure-gauge,vectorized_ranlux24_389_64) took 0.000308037 s
GPT :       0.543111 s : Lattice = [8, 8, 8, 16]
GPT :       0.543138 s : Actions:
GPT :       0.543150 s :  - mass_term(1.0)
GPT :       0.543160 s :  - wilson(5.96)
GPT :       0.543323 s : Integration scheme:
                       :  - Level 0 omf4 steps=5
                       :  - Level 1 euler steps=1
GPT :       0.543339 s : tau = 2.0 MD units
Traceback (most recent call last):
  File "/home/judah/Dropbox/lattice_gauge_gravity/pure_gauge.py", line 74, in <module>
    h += [hmc(tau, mom)]
  File "/home/judah/Dropbox/lattice_gauge_gravity/pure_gauge.py", line 61, in hmc
    h0 = hamiltonian()
  File "/home/judah/Dropbox/lattice_gauge_gravity/pure_gauge.py", line 37, in hamiltonian
    return a0(mom) + a1(U)
  File "/home/judah/gpt/lib/gpt/qcd/scalar/action/mass_term.py", line 30, in __call__
    return g.group.inner_product(pi, pi) * self.m * 0.5
  File "/home/judah/gpt/lib/gpt/core/group/operation.py", line 75, in inner_product
    return sum([inner_product(x, y) for x, y in zip(left, right)])
  File "/home/judah/gpt/lib/gpt/core/group/operation.py", line 75, in <listcomp>
    return sum([inner_product(x, y) for x, y in zip(left, right)])
  File "/home/judah/gpt/lib/gpt/core/group/operation.py", line 78, in inner_product
    return left_type.inner_product(left, right)
  File "/home/judah/gpt/lib/gpt/core/object_type/su_n.py", line 102, in inner_product
    return (gpt.sum(gpt(gpt.trace(left * right))) / self.trace_norm).real
  File "/home/judah/gpt/lib/gpt/core/operator/unary.py", line 134, in sum
    return l.grid.globalsum(rank_sum(l))
  File "/home/judah/gpt/lib/gpt/core/operator/unary.py", line 112, in rank_sum
    val = [cgpt.lattice_rank_sum(x) for x in l.v_obj]
  File "/home/judah/gpt/lib/gpt/core/operator/unary.py", line 112, in <listcomp>
    val = [cgpt.lattice_rank_sum(x) for x in l.v_obj]
AttributeError: module 'cgpt' has no attribute 'lattice_rank_sum'
=============================================
               Finalized GPT                 
=============================================
```

**Comment by lehner** [comment]
cgpt needs to be recompiled after a recent synchronization with upstream grid.  To make all work again:
1) pull the current  https://github.com/lehner/Grid feature-gpt branch and re-compile
2) re-compile cgpt

**Comment by jfy4** [comment]
When I attempt to recompile in step 1. it gives:

```
Making all in Grid
make[1]: Entering directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/build/Grid'
cp version-cache Version.h
make  all-am
make[2]: Entering directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/build/Grid'
  CXX      allocator/MemoryManagerShared.o
In file included from ../../Grid/allocator/MemoryManagerShared.cc:1:
In file included from /home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid/GridCore.h:43:
/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid/Namespace.h:31:10: fatal error: 'type_traits' file not found
#include <type_traits>
         ^~~~~~~~~~~~~
1 error generated.
make[2]: *** [Makefile:3050: allocator/MemoryManagerShared.o] Error 1
make[2]: Leaving directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/build/Grid'
make[1]: *** [Makefile:2285: all] Error 2
make[1]: Leaving directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/build/Grid'
make: *** [Makefile:528: all-recursive] Error 1
```

Any idea why this is now not found?

**Comment by lehner** [comment]
Can you share your Grid configure command line as well as your compiler + version?  type_traits is a standard header for C++11 (https://en.cppreference.com/w/cpp/header/type_traits) and it may be that your compiler does not support it.

**Comment by jfy4** [comment]
Ok, I followed the steps here: [https://github.com/lehner/Grid#quick-start](url) for configure and make, and at least there is a new issue and it is mpi:
```

Making all in Grid
make[1]: Entering directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid'
cp version-cache Version.h
make  all-am
make[2]: Entering directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid'
  CXX      allocator/MemoryManagerShared.o
In file included from /home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid/communicator/Communicator.h:32,
                 from /home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid/GridCore.h:55,
                 from allocator/MemoryManagerShared.cc:1:
/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid/communicator/SharedMemory.h:33:10: fatal error: mpi.h: No such file or directory
   33 | #include <mpi.h>
      |          ^~~~~~~
compilation terminated.
make[2]: *** [Makefile:3050: allocator/MemoryManagerShared.o] Error 1
make[2]: Leaving directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid'
make[1]: *** [Makefile:2285: all] Error 2
make[1]: Leaving directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid'
make: *** [Makefile:528: all-recursive] Error 1
Making check in Grid
make[1]: Entering directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid'
  CXX      allocator/MemoryManagerShared.o
In file included from /home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid/communicator/Communicator.h:32,
                 from /home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid/GridCore.h:55,
                 from allocator/MemoryManagerShared.cc:1:
/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid/communicator/SharedMemory.h:33:10: fatal error: mpi.h: No such file or directory
   33 | #include <mpi.h>
      |          ^~~~~~~
compilation terminated.
make[1]: *** [Makefile:3050: allocator/MemoryManagerShared.o] Error 1
make[1]: Leaving directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid'
make: *** [Makefile:528: check-recursive] Error 1
Making install in Grid
make[1]: Entering directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid'
  CXX      allocator/MemoryManagerShared.o
In file included from /home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid/communicator/Communicator.h:32,
                 from /home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid/GridCore.h:55,
                 from allocator/MemoryManagerShared.cc:1:
/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid/communicator/SharedMemory.h:33:10: fatal error: mpi.h: No such file or directory
   33 | #include <mpi.h>
      |          ^~~~~~~
compilation terminated.
make[1]: *** [Makefile:3050: allocator/MemoryManagerShared.o] Error 1
make[1]: Leaving directory '/home/judah/Dropbox/fermilab/gpt/dependencies/Grid/Grid'
make: *** [Makefile:528: install-recursive] Error 1
```

**Comment by lehner** [comment]
If you are attempting a local compile for use, say, within a Jupyter notebook, you may wish to compile without MPI support.  In this case changing the configure option "--enable-comms" to "--enable-comms=none" should work.

In the meantime I tried the scripts/bootstrap/debian10.clang.avx2.no-mpi script in an empty docker debian container and it works.  To understand better why this does not work for you, I would need more information such as your linux distribution etc.  Or maybe you are compiling on a Mac?

At any rate your quickest path to success may be to simply adopt the enable-comms flag above.

**Comment by jfy4** [comment]
Ok I have started over from scratch.  I believe I have installed Grid successfully.  I re-cloned gpt, and am attempting to compile cgpt using `./make <path to Grid>` and I receive the following:
`Need to configure Grid with -fPIC`
I'm not sure what this means I have to do, any advice?

**Comment by lehner** [comment]
Yes, please attempt to add CXXFLAGS="-fPIC" to the configure argument of
Grid.

**Comment by jfy4** [comment]
Is there an ideal location for Grid when I `configure`?

**Comment by lehner** [comment]
There are two locations that the cgpt make file will automatically find:

1) You have gpt and Grid in the same directory

2) You have Grid in gpt/dependencies/Grid

**Comment by jfy4** [comment]
When you say 'Grid' are you referring to the cloned directory, or the directory called 'Grid' that gets made from the `make; make check; make install` line?  I am try to figure out where to put the second one.

**Comment by lehner** [comment]
The cloned directory.  You do not need to install Grid.  It would be
sufficient, e.g., to do the following:

Go to your home directory ~, clone Grid and gpt such that they exist at
~/Grid and ~/gpt.  Create ~/Grid/build,
go to this directory and run ../configure ... of Grid and then make; make
check .  No need for make install.
Then go to ~/gpt/lib/cgpt and from this directory run ./make .

**Comment by jfy4** [comment]
That is helpful thank you, but I'm still not sure what <path> to provide in the configure step.  Does it even matter?

**Comment by jfy4** [comment]
pure_gauge.py runs now and it seems to be working.  Thank you for your patience and help.

**Comment by lehner** [comment]
Excellent!

jfy4 ***@***.***> schrieb am Mo. 9. Jan. 2023 um 9:09 PM:

**Comment by jfy4** [comment]
Hi Christopher,

I am trying to build Grid and gpt on the Wilson cluster at fermilab, and
when I run the bootstrap.sh for Grid I get the following:

./bootstrap.sh
-- deploying Eigen source...
--2023-03-08 10:45:20--
https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.bz2
Resolving gitlab.com (gitlab.com)... 172.65.251.78,
2606:4700:90:0:f22e:fbec:5bed:a9b9
Connecting to gitlab.com (gitlab.com)|172.65.251.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/octet-stream]
Saving to: ‘eigen-3.3.7.tar.bz2’

    [ <=>
  ] 1,663,474   --.-K/s   in 0.02s

2023-03-08 10:45:20 (78.8 MB/s) - ‘eigen-3.3.7.tar.bz2’ saved [1663474]

/usr/bin/sha256sum
eigen-3.3.7.tar.bz2: OK
patching file Eigen/unsupported/Eigen/CXX11/Tensor
Hunk #2 succeeded at 149 (offset 2 lines).
-- generating Make.inc files...
/work1/lqcd_gpt/Grid/tests
/work1/lqcd_gpt/Grid/tests/solver
/work1/lqcd_gpt/Grid/tests/testu01
/work1/lqcd_gpt/Grid/tests/debug
/work1/lqcd_gpt/Grid/tests/smearing
/work1/lqcd_gpt/Grid/tests/hmc
/work1/lqcd_gpt/Grid/tests/IO
/work1/lqcd_gpt/Grid/tests/forces
/work1/lqcd_gpt/Grid/tests/lanczos
/work1/lqcd_gpt/Grid/tests/qdpxx
/work1/lqcd_gpt/Grid/tests/core
-- generating configure script...
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force -I m4
autom4te: cannot create autom4te.cache: No such file or directory
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1


Any idea what these last errors are about?

Thanks,
Judah
