### ISSUE TITLE
Running on Summit

### ISSUE THREAD

**Issue by philomat** [lehner/gpt#88]
When I try to run gpt on summit I get runtime errors

I was trying to run with the dslash benchmark with the run_n1.sh script from the summit benchmark reference, where I adjusted the LD_LIBRARY_PATH and the source.sh location.

Here is the beginning of the error output:

`Warning: OMP_NUM_THREADS=6 is greater than available PU's`
`Warning: OMP_NUM_THREADS=6 is greater than available PU's`
`Warning: OMP_NUM_THREADS=6 is greater than available PU's`
`Warning: OMP_NUM_THREADS=6 is greater than available PU's`
`Warning: OMP_NUM_THREADS=6 is greater than available PU's`
`Warning: OMP_NUM_THREADS=6 is greater than available PU's`
`Traceback (most recent call last):`
`  File "dslash.py", line 7, in <module>`
`    import gpt as g`
`  File "/ccs/home/scior/gpt_summit/lib/gpt/__init__.py", line 19, in <module>`
`    from gpt.core import *`
`  File "/ccs/home/scior/gpt_summit/lib/gpt/core/__init__.py", line 20, in <module>`
`    from gpt.core.grid import grid, grid_from_description, full, redblack`
`  File "/ccs/home/scior/gpt_summit/lib/gpt/core/grid.py", line 19, in <module>`
`    import cgpt, gpt, sys`
`ImportError: /ccs/home/scior/gpt_summit/lib/cgpt/build/cgpt.so: undefined symbol: GOMP_critical_start
`

I compiled with an adapted version of the debian bootstrapping script, where my configure for Grid is:

`        ../configure \
    --enable-comms=mpi          \
    --enable-simd=GPU           \
    --enable-accelerator=cuda \
    --enable-unified=no \
    --prefix /ccs/home/scior/gpt_summit/dependencies/Grid/build       \
    --enable-summit \
    CXX=nvcc                    \
    LDFLAGS="-L/ccs/home/scior/prefix_summit/lib/" \
    CXXFLAGS="--compiler-options -fPIC -ccbin mpicxx -gencode arch=compute_70,code=sm_70 -I/ccs/home/scior/prefix_summit/include/ -std=c++11"`

There were no errors during compile time.

**Comment by philomat** [comment]
This works now
